//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fcAccount()
        {
            this.fcUserAccounts = new HashSet<fcUserAccount>();
            this.fcWebpages = new HashSet<fcWebpage>();
        }
    
        public int PK { get; set; }
        public string Name { get; set; }
        public string AccountID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fcUserAccount> fcUserAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fcWebpage> fcWebpages { get; set; }
    }
}
