//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastAnalysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fcUserAccount
    {
        public int PK { get; set; }
        public Nullable<int> UserFK { get; set; }
        public Nullable<int> AccountFK { get; set; }
    
        public virtual fcAccount fcAccount { get; set; }
        public virtual fcUser fcUser { get; set; }
    }
}
